// Generated by CoffeeScript 1.3.3
(function() {
  var Collate, EventEmitter, async, coffee, compilationError, fs, jsp, less, path, pro, wait, _Collator,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  fs = require('fs');

  path = require('path');

  async = require('async');

  coffee = require('coffee-script');

  less = require('less');

  jsp = require('uglify-js').parser;

  pro = require('uglify-js').uglify;

  EventEmitter = require('events').EventEmitter;

  wait = function(milliseconds, func) {
    return setTimeout(func, milliseconds);
  };

  compilationError = 'compilation error';

  Collate = (function() {

    function Collate() {}

    Collate.prototype.collate = function(target, sources, options, callback) {
      var collator, _ref, _ref1;
      if (options == null) {
        options = {};
      }
      if ((_ref = options.compress) == null) {
        options.compress = true;
      }
      if ((_ref1 = options.verbose) == null) {
        options.verbose = false;
      }
      collator = new _Collator(target, sources, options, callback);
      collator.collate();
      return collator;
    };

    return Collate;

  })();

  _Collator = (function(_super) {

    __extends(_Collator, _super);

    function _Collator(target, sources, options, callback) {
      var source,
        _this = this;
      this.target = target;
      this.sources = sources;
      this.options = options;
      this.callback = callback;
      this._writeTarget = __bind(this._writeTarget, this);

      this._compileSource = __bind(this._compileSource, this);

      this._compileSources = __bind(this._compileSources, this);

      this._rewatch = __bind(this._rewatch, this);

      this._watchEvent = __bind(this._watchEvent, this);

      this.collate = __bind(this.collate, this);

      if (options.basedir != null) {
        this.target = path.join(this.options.basedir, this.target);
        this.sources = (function() {
          var _i, _len, _ref, _results;
          _ref = this.sources;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            source = _ref[_i];
            _results.push(path.join(this.options.basedir, source));
          }
          return _results;
        }).call(this);
      }
      this.target = path.resolve(this.target);
      this.sources = (function() {
        var _i, _len, _ref, _results;
        _ref = this.sources;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          source = _ref[_i];
          _results.push(path.resolve(source));
        }
        return _results;
      }).call(this);
      async.map(this.sources, fs.stat, function(err, stats) {
        if (err) {
          console.error(err);
          return _this.options.watch = false;
        } else {
          return _this._stats = stats;
        }
      });
    }

    _Collator.prototype.collate = function() {
      var _this = this;
      return async.series([this._compileSources, this._writeTarget], function(err, results) {
        var msg;
        if (!err) {
          msg = "" + ((new Date).toLocaleTimeString()) + " - collated " + (path.basename(_this.target));
          _this.emit('collate', msg);
          if (_this.options.verbose) {
            console.log(msg);
          }
        }
        if (err && err !== compilationError) {
          _this.emit('error', err);
          console.error(err);
        }
        if (_this.callback != null) {
          _this.callback(err);
        }
        if (_this.options.watch) {
          return _this._rewatch();
        }
      });
    };

    _Collator.prototype._watchEvent = function(event, filename) {
      var _this = this;
      clearTimeout(this._watchTimeout);
      return this._watchTimeout = wait(100, function() {
        var watcher, _i, _len, _ref;
        _ref = _this._watchers;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          watcher = _ref[_i];
          watcher.close();
        }
        return async.map(_this.sources, fs.stat, function(err, stats) {
          var i, msg, prev, stat, _j, _len1;
          for (i = _j = 0, _len1 = stats.length; _j < _len1; i = ++_j) {
            stat = stats[i];
            prev = _this._stats[i];
            if (stat.size !== prev.size || stat.mtime.getTime() !== prev.mtime.getTime()) {
              msg = "" + ((new Date).toLocaleTimeString()) + " - " + (path.basename(_this.sources[i])) + " changed";
              _this.emit('change', msg);
              if (_this.options.verbose) {
                console.log(msg);
              }
              _this._compiledSources[i] = null;
              _this._stats[i] = stat;
            }
          }
          if (_this._compiledSources.indexOf(null) !== -1) {
            return _this.collate();
          } else {
            return _this._rewatch();
          }
        });
      });
    };

    _Collator.prototype._rewatch = function() {
      var source;
      return this._watchers = (function() {
        var _i, _len, _ref, _results;
        _ref = this.sources;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          source = _ref[_i];
          _results.push(fs.watch(source, this._watchEvent));
        }
        return _results;
      }).call(this);
    };

    _Collator.prototype._compileSources = function(callback) {
      var compileIfChanged, i, source, _i, _j, _len, _ref, _ref1, _results,
        _this = this;
      if (!this._compiledSources) {
        this._compiledSources = [];
        _ref = this.sources;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          source = _ref[i];
          this._compiledSources[i] = null;
        }
      }
      compileIfChanged = function(i, _callback) {
        if (!(_this._compiledSources[i] != null)) {
          return _this._compileSource(_this.sources[i], function(err, result) {
            if (result) {
              _this._compiledSources[i] = result;
            } else {
              _this._compiledSources[i] = compilationError;
            }
            return _callback(null);
          });
        } else {
          return _callback(null);
        }
      };
      return async.map((function() {
        _results = [];
        for (var _j = 0, _ref1 = this._compiledSources.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; 0 <= _ref1 ? _j++ : _j--){ _results.push(_j); }
        return _results;
      }).apply(this), compileIfChanged, callback);
    };

    _Collator.prototype._compileSource = function(source, callback) {
      var compile, compress, ext, read, uglify;
      ext = path.extname(source);
      compress = this.options.compress;
      uglify = function(js) {
        var ast;
        try {
          ast = jsp.parse(js);
        } catch (e) {
          console.error("In " + (path.basename(source)) + ", line " + e.line + ", col " + e.col + " - " + e.message);
          return null;
        }
        ast = pro.ast_mangle(ast);
        ast = pro.ast_squeeze(ast);
        return pro.gen_code(ast);
      };
      read = function(_callback) {
        return fs.readFile(source, _callback);
      };
      compile = function(result, _callback) {
        var less_options;
        result = result.toString();
        switch (ext) {
          case '.js':
            if (compress) {
              result = uglify(result);
            }
            return _callback(null, result);
          case '.coffee':
            try {
              result = coffee.compile(result);
            } catch (e) {
              console.error("In " + (path.basename(source)) + " - " + e);
              result = null;
            }
            if (compress && result) {
              result = uglify(result);
            }
            return _callback(null, result);
          case '.css':
          case '.less':
            less_options = {
              filename: source,
              paths: [path.dirname(source)]
            };
            return new less.Parser(less_options).parse(result, function(e, tree) {
              var logLessErr;
              logLessErr = function(e) {
                return console.error("In " + (path.basename(source)) + ", line " + e.line + ", col " + e.column + " - " + e.type + ": " + e.message);
              };
              if (e) {
                logLessErr(e);
                result = null;
              } else {
                try {
                  result = tree.toCSS({
                    compress: compress
                  });
                } catch (e) {
                  logLessErr(e);
                  result = null;
                }
              }
              return _callback(null, result);
            });
        }
      };
      return async.waterfall([read, compile], callback);
    };

    _Collator.prototype._writeTarget = function(callback) {
      var compiledSource, ws, _i, _len, _ref;
      if (this._compiledSources.indexOf(compilationError) === -1) {
        ws = fs.createWriteStream(this.target);
        _ref = this._compiledSources;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          compiledSource = _ref[_i];
          ws.write(compiledSource);
          if (this.target.indexOf('.js') !== -1 && this.options.compress) {
            ws.write(';\n');
          }
        }
        ws.end();
        return callback(null);
      } else {
        return callback(compilationError);
      }
    };

    return _Collator;

  })(EventEmitter);

  module.exports = new Collate;

}).call(this);
